### ISSUE TITLE
handle multiple page capi queries

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/capi-wpt-querybot#14]
capi queries beyond a certain size will time out - need to be able to handle this - ie split query into two or something

**Comment by mchv** [comment]
@michaelwmcnamara more details on the requests that are timing out, as it should not be the case?

**Comment by michaelwmcnamara** [comment]
Hi Mariot,
I will try reproduce and add detail on Monday.
All the best

Mike

**Comment by michaelwmcnamara** [comment]
done
